cleanDeviceName rewritten to remove all _ labels and remove search list and local domain
jokob-sk/NetAlertX pull request #650
Opened 2024-04-23 13:34 UTC by ulrichwisser

This change introduces a new dependency to dnspython. 

It removes all labels starting with an underscore.

It does not remove specific domain names like lan, home, ... Instead it removes the domain of the local network and even the search list of the local network.

I have not seen test cases for domain names. It would be really helpfull to collect names and how the users want them to change. For that even the local DNS config would be needed (domain and search list from /etc/resolv.conf)

This is potentially a big change. How can we test this?

2024-04-23 21:17 UTC, jokob-sk requested changes
Thanks for the PR!

Please use the below method to log output:
```
mylog('none','[upgradeDB] Table is incompatible, Dropping the Online_History table')
```

In this case, since it's intentionally a big change, let us implement a feature flag. 

Let's keep the original behavior in place by default and add a setting, e.g. "CLEAN_NAME" which would be by default set to `true`. 

You can initialize this setting in the NEWDEV plugin in thesettings section of the config: https://github.com/jokob-sk/NetAlertX/blob/main/front/plugins/newdev_template/config.json

Then you can access the value with the get_setting_value("NEWDEV_CLEAN_NAME") , if set to false, your code branch would be executed. 

This way we can introduce a feature without breaking changes

2024-04-24 11:12 UTC, ulrichwisser commented
I tried to do these changes in my instance, but how can I access the newdev settings?

2024-04-24 11:13 UTC, ulrichwisser commented
And how do I enable debug logging?

2024-04-24 11:53 UTC, jokob-sk commented
You can access the setting via get_setting_value("NEWDEV_CLEAN_NAME"). To enable debug logging see this doc: https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md

2024-04-24 12:08 UTC, ulrichwisser commented
Can I access the config through the web ui?

2024-04-24 12:27 UTC, jokob-sk commented
yes, once you define it in teh aforementioned config.json, it will automatically show in the settings > newdev section

2024-04-24 12:58 UTC, ulrichwisser commented
My instance doesn't show me that configuration. I am running the docker container  jokobsk/netalertx:latest

2024-04-24 13:03 UTC, jokob-sk commented
hummm, can you show me how you defined the new setting in the `config.json`: https://github.com/jokob-sk/NetAlertX/blob/main/front/plugins/newdev_template/config.json

2024-04-24 13:09 UTC, ulrichwisser commented
I do not have a newdev section at all. In the setting menu I have only the following sections 
Enabled settings
Core
System
Device scanners
Other scanners
Publishers

2024-04-24 13:11 UTC, jokob-sk commented
Ah I see, it's here, under System: 
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/55165a9f-39fa-4370-a463-71375e7ee6c4)

2024-04-24 21:54 UTC, jokob-sk commented
Thanks a lot for the submission and glad to hear it's almost done :) I left a couple of comments to keep the code somewhat consistent. Thanks for the help!

2024-04-28 00:46 UTC, jokob-sk reviewed
Hey, I reviewd teh PR - once these changes are done the PR is ready to merge

2024-04-28 00:46 UTC, jokob-sk commented on front/plugins/newdev_template/config.json
> +              "string": "Use new algorithm to cleanup device names"
This is the label and shouldn't be this long as it will break the UI on smaller screens, Maybe: "Less Name Cleanup"

2024-04-28 00:46 UTC, jokob-sk commented on front/plugins/newdev_template/config.json
> +          "function": "dev_CleanDeviceName",
I know it's not apparent, but `dev_` prefixes indicate database columns in the Devices table, just use something like "LESS_NAME_CLEANUP" - I know naming is hard :)

2024-04-28 00:46 UTC, jokob-sk commented on server/helper.py
> +def NEW_cleanDeviceName(str, match_IP):
Lastly, let's keep the code in one method - logically the method cleanDeviceName is still valid, there are just two ways how to do it now.

2024-04-28 00:46 UTC, jokob-sk commented on server/helper.py
> +import dns.resolver
if you need an additional python package you need to update the following files:

https://github.com/jokob-sk/NetAlertX/blob/ecf6c1848d8947d737ee826be1c99038a346ded0/install/install_dependencies.debian.sh#L33

https://github.com/jokob-sk/NetAlertX/blob/ecf6c1848d8947d737ee826be1c99038a346ded0/Dockerfile#L15

2024-04-30 22:20 UTC, jokob-sk approved these changes
Looks great, thank you! 🙏

2024-04-30 22:25 UTC, merged